### ISSUE TITLE
webworkers module unable to load

### ISSUE THREAD

**Issue by freshsocks** [touchads/node-wurfl-api#1]
I'm pretty new to all of this still so sorry I can't be more specific.

I added var wurfl = require('wurfl');
Upon running app, wurfl couldn't find the node-expat module.
After $npm install node-expat in the wurfl node_modules dir, I get a similar error, this time it couldn't find webworkers module.
Tried to $npm install webworkers in the same way but it still wouldn't read.
I just deleted everything from the wurfl.js file that uses webworkers in order to use it. Still haven't tried actually implementing it but I just wanted to let you know that it broke my app by simply requiring it. 

Thanks, wish I could help more.

**Comment by jacwright** [comment]
The problem is the modules are not updated to work with the latest node. Updating node-expat to the latest did fix the first issue as you found. Webworkers is still broken. I will try and get an alternative library to fix this or simply remove webworkers. Thank you for submitting the issue!

**Comment by jacwright** [comment]
I've updated node-expat to 1.4.1 and replaced webworkers with backgrounder. Published 0.3.0 to NPM. wurfl is now working as it should. Just do another `npm install wurfl` to update.
