### ISSUE TITLE
Won't detect device

### ISSUE THREAD

**Issue by arneldomingo** [touchads/node-wurfl-api#12]
Using the latest wurfl.xml, the API won't detect user agents like this:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.99 Safari/537.22

Mozilla/5.0 (Windows NT 6.1; Intel Mac OS X 10.6; rv:7.0.1) Gecko/20100101 Firefox/7.0.1

And others.

Here is my code:

var deviceInfo = wurfl.get(req.headers['user-agent']);

deviceInfo is just undefined.

**Comment by miguelmota** [comment]
I'm experiencing this same issue.
It won't detect a lot of user agents.

For example

```
Mozilla/5.0 (Linux; U; Android 2.1; en-us; Nexus One Build/ERD62) AppleWebKit/530.17 (KHTML, like Gecko) Version    /4.0 Mobile Safari/530.17
```

returns `undefined`.

**Comment by jacwright** [comment]
I don't have time to get into this right now. If you're able to figure out what is wrong and submit pull-request fix I'll gladly merge it. Sorry, and thanks.

**Comment by tobsn** [comment]
same here - we tried to include it into a current project and pretty much everything but the example returns undefined.

**Comment by jacwright** [comment]
This project is intended to be a utility to return the capabilities of devices found in the wurfl.xml file by user agent. It is designed to be memory efficient as this file is quite sizable. That is all this project does.

If the user agent doesn't exist in the wurfl.xml file, you receive an undefined. The wurfl.xml file can be updated here: http://sourceforge.net/projects/wurfl/files/WURFL/ and provides an easy way to look at a device's capabilities, when the device is known.

This project makes no guarantees about what is in the wurfl.xml file. If it is missing a lot of user agents I would go look more at http://wurfl.sourceforge.net/ and find out more and/or log a ticket there.

There may be ways to make the lookup "fuzzy" to find similar devices better. I welcome any pull-requests to make this better.
