### ISSUE TITLE
Cannot detect iPhone

### ISSUE THREAD

**Issue by art1c0** [touchads/node-wurfl-api#13]
There should be something wrong with your library, as it doesn't detect even an iPhone.
At the same time, PHP wurfl module can do that using the same wurfl.xml file (checked).

User-Agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25

Code:
var wurfl = require('wurfl');
wurfl.loadSync();
var ua = 'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25';
var info = wurfl.get(ua);
// info is undefined

Tried both wurfl.xml files: bundled with the library (which version is 2.2), and also pretty new xml of version 2.3.5.

Again, wurfl.xml file is totally working and definitely has info about the iPhone, that's confirmed by testing of these wurfl.xml files against the same user-agent provided, but using PHP wrapper. iPhone is detected by these wurfl.xml files with no problem.

Please check, as this is important since your library seems to be the only wurfl wrapper for node.

**Comment by jacwright** [comment]
I will deprecate the library on the home page and allow someone else to take over it.
