### ISSUE TITLE
Api retunred undefined for droid global user agent

### ISSUE THREAD

**Issue by ghost** [touchads/node-wurfl-api#2]
'Mozilla/5.0 (Linux; U; Android 2.3.3; en-us; DROID2 GLOBAL Build/4.5.1_57_D2G-38) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1';

**Comment by jacwright** [comment]
You may want to try using an updated version of wurfl.xml. We don't regularly update it in the repository. Also after the initial load/loadSync you can use watch so that you can update the wurfl.xml file without restarting the node process.

**Comment by tobsn** [comment]
watch?

**Comment by jacwright** [comment]
See the [documentation](https://github.com/touchads/node-wurfl-api) about watching:

> When using your own file, it would be great to update the file without needing to restart the node.js server:
> 
> ``` javascript
> wurfl.watch(myWurflFile);
> ```
