### ISSUE TITLE
I keep getting undefined with .get method

### ISSUE THREAD

**Issue by valeeum** [touchads/node-wurfl-api#5]
I keep getting undefined for device when I try to access my node app with my iPhone and my browser.  However, when I use the user agent provided in the example, 'Mozilla/4.0 (compatible; MSIE 4.01; Windows CE; O2 Xda 2s;PPC;240x320; PPC; 240x320)', i get a valid output.  Can someboy explain why this is the case?

var userAgent = request.headers;
console.log(userAgent);
var deviceInfo = wurfl.get(userAgent);
console.log(deviceInfo);

Using FIrefox:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:12.0) Gecko/20100101 Firefox/12.0
undefined

Using iPhone:
Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B176 Safari/7534.48.3
undefined

**Comment by jacwright** [comment]
It is because those user agents do not exist in the WURFL file. If they exist, you get the data. If they don't, you get undefined. I wrote the library to make the wurfl.xml file easier to use. I don't know much about the data included and why some agents get included and some don't.
