### ISSUE TITLE
WURFL for Node.js

### ISSUE THREAD

**Issue by passani** [touchads/node-wurfl-api#8]
Hi there, Luca Passani, WURFL Creator here.

I found this project on GitHub and I would like to observe that it is missing all the logic that comes with the standard WURFL API.
While ScientiaMobile does not support Node.js in the form of a standalone API, we do support it in our Cloud solution (this link has more info: http://www.scientiamobile.com/wurflCloud/gettingStarted/ ).

Would it be possible for the author to reference this in the main page of this project?

Thank you

Luca Passani
WURFL Creator and CTO @ScientiaMobile

**Comment by jacwright** [comment]
Sure thing.
